"""realspace_exactdiagonalization_py — Python port of
``RealSpace_ExactDiagonalization.jl``.

Symmetry-resolved exact diagonalization on arbitrary real-space graphs for
hard-core bosons and spinless fermions, in matrix and matrix-free modes
(see :mod:`realspace_exactdiagonalization_py.symmetry_resolved_ed` for the
engine documentation and the XDiag references).
"""

from .utils.bitwise_operations import (
    COMPLEX_ONE,
    MAX_N_SITE_UINT64,
    Mask,
    bitmask_of_site,
    decode_bit_mask_to_configuration,
    decode_bit_mask_to_configuration_inplace,
    empty_site_for_mask,
    empty_site_iter_for_mask,
    encode_configuration_to_bit_mask,
    filled_site_iter_for_mask,
    is_site_empty,
    is_site_occupied,
    n_occupied_for_mask,
    occupy_site_for_mask,
)
from .second_quantized_model import (
    Particle_Statistics,
    Real_Space_Second_Quantized_Model,
    update_second_quantized_model_with_twisted_phases,
)
from .symmetry_resolved_ed import (
    CanonicalMap,
    build_matrixfree_projection_table,
    rank_combination,
    Finite_Symmetry_Group,
    MatrixFreeHamiltonian,
    OneDim_Irrep,
    Symmetry_Operation,
    Symmetry_Orbit_Catalog,
    Symmetry_Resolved_ED_Data,
    Symmetry_Sector_Basis,
    apply_hamiltonian,
    apply_hamiltonian_with_threads,
    apply_operation_to_mask,
    build_ed_Hamiltonian_symmetry_block,
    build_ed_data,
    build_identity_group,
    build_identity_irrep_list,
    build_irrep_list,
    build_symmetry_orbit_catalog,
    build_symmetry_sector_basis,
    build_translation_group,
    build_translation_irrep_list,
    diagonalize_block_arpack,
    diagonalize_block_dense,
    diagonalize_block_matrixfree,
    ed_scan,
    ed_scan_at_irrep_matrix,
    ed_scan_at_irrep_matrixfree,
    ed_scan_checkpoint_filename,
    full_ed,
    get_canonical,
    get_canonical_representative,
    group_order,
    hamiltonian_linear_operator,
    hopping_phase_for_stats,
    load_checkpoint,
    plot_ed_scan_res,
    plot_spectrum,
    populate_canonical_map,
    print_spectrum,
    project_to_sector,
    project_to_unnormalized_sector,
    save_checkpoint,
    update_orbit_stabilizer_phases,
)
from .observables import (
    compute_odlro_map,
    compute_structure_factor_manifold_average_map,
    compute_structure_factor_map,
    entanglement_spectrum,
    flux_charge_pump,
    flux_spectrum_flow,
    many_body_chern_number,
    many_body_position_phases,
    off_diagonal_long_range_order,
    particle_entanglement_spectrum,
    plot_entanglement_spectrum,
    plot_odlro_map,
    plot_odlro_map_panels,
    plot_particle_entanglement_spectrum,
    plot_structure_factor_allowed_momenta,
    plot_structure_factor_allowed_momenta_panels,
    plot_structure_factor_map,
    plot_structure_factor_map_panels,
    static_structure_factor,
    static_structure_factor_manifold_average,
    structure_factor_allowed_momenta,
    structure_factor_manifold_allowed_momenta,
    vertices_occupation_distribution_full_ed,
)
from .models import (
    CHECKERBOARD_TPP_DENOMINATOR,
    build_heisenberg_ed_data,
    build_heisenberg_second_quantized_model,
    build_phase_explore_fermionic_checkerboard_model,
    build_spinful_hubbard_ed_data,
    build_spinful_hubbard_second_quantized_model,
    build_bosonic_fci_ed_data,
    build_fermionic_checkerboard_tb_model,
    build_fermionic_fci_ed_data,
    build_zero_flux_bosonic_fci_second_quantized_model,
    build_zero_flux_fermionic_fci_second_quantized_model,
    default_fci_sectors,
    default_fci_sectors_fermionic,
    params_DNSheng,
    params_Sun_Gu_Katsura_Sarma,
    test_bosonic_fci_charge_pump,
    test_bosonic_fci_spectrum_flow,
    test_fermionic_fci_charge_pump,
    test_fermionic_fci_full_ed,
    test_fermionic_fci_spectrum_flow,
)

__version__ = "0.1.0"


def main() -> None:
    """Console entry point placeholder (kept minimal on purpose)."""
    print(
        "realspace_exactdiagonalization_py — symmetry-resolved exact "
        "diagonalization. See README.md and doc/*.ipynb for usage."
    )


__all__ = [
    # bitwise operations
    "Mask",
    "COMPLEX_ONE",
    "MAX_N_SITE_UINT64",
    "bitmask_of_site",
    "occupy_site_for_mask",
    "empty_site_for_mask",
    "is_site_occupied",
    "is_site_empty",
    "n_occupied_for_mask",
    "filled_site_iter_for_mask",
    "empty_site_iter_for_mask",
    "encode_configuration_to_bit_mask",
    "decode_bit_mask_to_configuration",
    "decode_bit_mask_to_configuration_inplace",
    # second-quantized model
    "Particle_Statistics",
    "Real_Space_Second_Quantized_Model",
    "update_second_quantized_model_with_twisted_phases",
    # symmetry-resolved ED
    "Symmetry_Operation",
    "Finite_Symmetry_Group",
    "group_order",
    "OneDim_Irrep",
    "Symmetry_Orbit_Catalog",
    "Symmetry_Sector_Basis",
    "CanonicalMap",
    "build_matrixfree_projection_table",
    "rank_combination",
    "MatrixFreeHamiltonian",
    "Symmetry_Resolved_ED_Data",
    "apply_operation_to_mask",
    "get_canonical_representative",
    "get_canonical",
    "populate_canonical_map",
    "project_to_sector",
    "project_to_unnormalized_sector",
    "hopping_phase_for_stats",
    "apply_hamiltonian",
    "apply_hamiltonian_with_threads",
    "hamiltonian_linear_operator",
    "build_ed_Hamiltonian_symmetry_block",
    "diagonalize_block_dense",
    "diagonalize_block_arpack",
    "diagonalize_block_matrixfree",
    "build_identity_group",
    "build_translation_group",
    "build_identity_irrep_list",
    "build_translation_irrep_list",
    "build_irrep_list",
    "build_symmetry_orbit_catalog",
    "update_orbit_stabilizer_phases",
    "build_symmetry_sector_basis",
    "build_ed_data",
    "full_ed",
    "ed_scan",
    "ed_scan_at_irrep_matrix",
    "ed_scan_at_irrep_matrixfree",
    "save_checkpoint",
    "load_checkpoint",
    "ed_scan_checkpoint_filename",
    "print_spectrum",
    "plot_spectrum",
    "plot_ed_scan_res",
    # observables
    "flux_spectrum_flow",
    "many_body_position_phases",
    "flux_charge_pump",
    "vertices_occupation_distribution_full_ed",
    "static_structure_factor",
    "structure_factor_allowed_momenta",
    "static_structure_factor_manifold_average",
    "structure_factor_manifold_allowed_momenta",
    "compute_structure_factor_map",
    "compute_structure_factor_manifold_average_map",
    "plot_structure_factor_map",
    "plot_structure_factor_map_panels",
    "plot_structure_factor_allowed_momenta",
    "plot_structure_factor_allowed_momenta_panels",
    "off_diagonal_long_range_order",
    "compute_odlro_map",
    "plot_odlro_map",
    "plot_odlro_map_panels",
    "entanglement_spectrum",
    "plot_entanglement_spectrum",
    "particle_entanglement_spectrum",
    "plot_particle_entanglement_spectrum",
    "many_body_chern_number",
    # models
    "params_DNSheng",
    "build_zero_flux_bosonic_fci_second_quantized_model",
    "build_bosonic_fci_ed_data",
    "default_fci_sectors",
    "test_bosonic_fci_spectrum_flow",
    "test_bosonic_fci_charge_pump",
    "params_Sun_Gu_Katsura_Sarma",
    "CHECKERBOARD_TPP_DENOMINATOR",
    "build_fermionic_checkerboard_tb_model",
    "build_zero_flux_fermionic_fci_second_quantized_model",
    "build_fermionic_fci_ed_data",
    "default_fci_sectors_fermionic",
    "test_fermionic_fci_full_ed",
    "test_fermionic_fci_spectrum_flow",
    "test_fermionic_fci_charge_pump",
    "build_heisenberg_second_quantized_model",
    "build_heisenberg_ed_data",
    "build_spinful_hubbard_second_quantized_model",
    "build_spinful_hubbard_ed_data",
    "build_phase_explore_fermionic_checkerboard_model",
]
